### ISSUE TITLE
URI Encode and Documentation

### ISSUE THREAD

**Issue by delsonting** [jaredrileysmith/callrail-gtm-template#1]
This template has been approved for the Gallery and should be live in the next day. Two recommendations:
1) URI Encode user provided values in the url on line 89 of your [template](https://github.com/jaredrileysmith/callrail-gtm-template/blob/master/template.tpl) to make sure the user provided values are safe for use as url parameters
2) Provide instructions on how to deploy the tag in the README

**Comment by jaredrileysmith** [comment]
1. The validation rules in place for the user input, beginning on lines 50 and 69, assure that the input is URL safe.
2. I will add the appropriate documentation in README, once complete I will close the issue.

**Comment by jaredrileysmith** [comment]
![image](https://user-images.githubusercontent.com/26010307/70359815-751d8b00-1842-11ea-98f5-caba9f0a91b1.png)

**Comment by jaredrileysmith** [comment]
Updated template to URI encode user provided input to in order to adhere to best practices and added detailed instructions on template deployment in README.  Closing issue.
